version: '3.4'

services:
  api-gateway:
    build: .
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 8000
      FILE_SERVICE_URL: "http://file-service:8000/api"
      STORAGE_SERVICE_URL: "http://storage-service:8000/api"
      SPIKE_ENABLED: true
      SPIKE_AUDIENCE: 2rYAQb~MpuJ5JDk~yBc2tk6wgajjPy
      SPIKE_PUBLIC_KEY_DOWNLOAD_URI: https://ospike.northeurope.cloudapp.azure.com/.well-known/publickey.pem
      SHRAGA_ENABLED: true
      SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
      SHRAGA_CALLBACK_URL: http://localhost:8000/auth/callback
    ports:
      - 8000:8000
