version: '3.4'

services:
  api-gateway:
    build: .
    ports:
      - 8000:8000
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      PORT: 8000
      SPIKE_ENABLED: true
      SPIKE_AUDIENCE: 2rYAQb~MpuJ5JDk~yBc2tk6wgajjPy
      SPIKE_PUBLIC_KEY_DOWNLOAD_URI: https://ospike.northeurope.cloudapp.azure.com/.well-known/publickey.pem
      SHRAGA_ENABLED: true
      SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
      SHRAGA_CALLBACK_URL: http://localhost:8000/auth/callback
      FS_CRUD_URL: http://localhost:8001
      STORAGE_SERVICE_URL: http://localhost:8002
      KARTOFFEL_URL: http://kartoffel.branch-yesodot.org
      LINK_SECRET: secret
      SPIKE_CLIENTS_API_SCOPE: api
